name: hydrated_theme_mode_bloc
description: A hydrated bloc for ThemeMode
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  hydrated_bloc: ^9.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  build_runner: ^2.4.12
  import_sorter: ^4.6.0
  mockito: ^5.4.4
  very_good_analysis: ^6.0.0
